### ISSUE TITLE
DiffElement `has_diffs()` method not returning booleans as expected

### ISSUE THREAD

**Issue by PhillSimonds** [networktocode/diffsync#38] opened 2020-11-11 02:59 UTC
### Environment
* DiffSync version:  1.0.0
* Python version  3.7.2

### Observed Behavior
When a `.has_diffs()` call is made to a `diffsync.diff.DiffElement` object, the object returns False when children do, indeed, have diffs. This occurs whether or not the `include_children=True` argument is passed into the method call.

### Expected Behavior
I expected `.has_diffs()` to evaluate to `True` in the case that diffs do not exist in the parent object but do exist in one of the children, and for the method to also evaluate to True when `include_children=True` is passed in as an argument and diffs exist in the children

### Steps to Reproduce
1. Create a DiffSyncModel child class for provider with attributes `slug`, `name`, and `site`. Add the `slug` to the `_identifiers` tuple, `name` to the `_attributes` tuple, and a dictionary of {'site': 'sites'} to the `_children` attribute.
2. Create a DiffSyncModel child class for site with the attribute `name` and `slug`
3. Create a DiffSync child class to represent a netbox backend. Define a load() method to load regions and sites from netbox, ensuring sites are added as children of regions using the add_child method. Make the `top_level` attribute `regions`
4. Create a DiffSync child class to represent a YAML backend. Define a load() method to load regions and sites from YAML files, ensuring sites are added as children of regions using the add_child method. Make the `top_level` attribute `regions`
5. Modify the data such that a diff exists between the YAML data and the Netbox data for a site within a given region, but data for the the region does not differ.
6. Define a `sync_from()` method on the YAML backend taking one argument of `source` and define a break point (or a pdb.set_trace() inside the method.
7. Write code that calls sync_from() on the YAML backend, passing in the instantiated netbox backend as the `source` argument.
8. Execute the code. When you get a pdb shell, run the following commands:
```
diff = self.diff_from(source)
regions = [region for region in diff.get_children]
regions[0].has_diffs()
regions[0].has_diffs(include_children=True)
```
Observe that the region who's children has diffs does not itself show any diffs, regardless of whether `include_children` is passed in as an argument or not.

**Comment by itdependsnetworks** [comment] 2020-11-11 03:17
Not really my place, but as an outsider would suggest providing code as an example, rather than explaining how to build the code may be beneficial.

**Comment by glennmatthews** [comment] 2020-11-11 14:37
@PhillSimonds The only way I've been able to reproduce this issue so far is if the child objects (in your case, `Site` models) are not added to the base `DiffSync` instance (i.e., you've called `region.add_child(site)` to store the UID of the site in the `Region` model, but have not called `netbox_backend.add(site)` to store the actual `site` object in the `netbox_backend` instance. In that case, when diffing the children of the `region` object, the referenced `site` objects cannot be found by the DiffSync, and it (currently) silently skips over them in the diff calculation.

Can you check whether this is the case in your code and let me know?

If so, the root cause is that currently `DiffSync.get_by_uids()` skips over any uids that it isn't able to find, and doesn't report any error in that case - I think I will change this behavior, as I think it's a source of non-obvious problems like this one.

If not, please do provide a worked example demonstrating the issue as suggested by @itdependsnetworks, as I'm otherwise unable to reproduce this issue so far. Thanks!

**Comment by glennmatthews** [comment] 2020-11-18 19:26
Opened https://github.com/networktocode/diffsync/pull/43 for the `get_by_uids()` change/fix.

**Comment by glennmatthews** [comment] 2021-04-02 17:49
Closing this as unreproducible - feel free to re-open with additional details if this is still an issue for you.

**Closed by glennmatthews** 2021-04-02 17:49 UTC
Labels: bug, question
